trigger:
- master

pool:
  name: Default  # Using your self-hosted agent pool

variables:
  feedName: 'assignment04'
  feedUrl: 'https://pkgs.dev.azure.com/mshar246/Assignment04/_packaging/assignment04/nuget/v3/index.json'

steps:
# Step 1: Install NuGet (in case any restore is needed)
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

# Step 2: Restore dependencies (optional for SDK projects, but safe)
- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: restore
    restoreSolution: 'Manav_DevOps_Assignment4.sln'

# Step 3: Build the project using dotnet
- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: 'ShowCase/ShowCase.csproj'
    arguments: '--configuration Release'

# Step 4: Pack using dotnet (works with SDK-style csproj)
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package using dotnet CLI'
  inputs:
    command: 'pack'
    packagesToPack: 'ShowCase/ShowCase.csproj'
    configuration: 'Release'
    outputDir: '$(Build.ArtifactStagingDirectory)/nupkg'

# Step 5: Push the package to Azure Artifacts
- task: NuGetCommand@2
  displayName: 'Push NuGet Package to Azure Artifacts'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/nupkg/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'assignment04'


# Step 6 (Optional): Commit YAML file to GitHub (you can remove this if not needed)
- script: |
    git add .
    git commit -m "Update Azure Pipeline YAML"
    git push origin master
  displayName: 'Push YAML File to GitHub'
