trigger:
- master

pool:
  name: Default  # Using the self-hosted agent pool, "Default"

variables:
  feedName: 'assignment04'
  feedUrl: 'https://pkgs.dev.azure.com/mshar246/Assignment04/_packaging/MyNugetFeed/nuget/v3/index.json'

steps:

# Step 1: Install NuGet tool
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

# Step 2: Restore NuGet packages
- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: 'Manav_DevOps_Assignment4.sln'
  displayName: 'Restore NuGet Packages'

# Step 3: Build the project and output to a known location
- task: MSBuild@1
  inputs:
    solutionFile: 'Manav_DevOps_Assignment4.sln'
    msbuildArguments: '/p:Configuration=Release /p:OutputPath=$(Build.ArtifactStagingDirectory)/bin'
  displayName: 'Build Project'

# Step 4: Pack the NuGet package
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'ShowCase/ShowCase.csproj'
    versioningScheme: 'off'
    outputDir: '$(Build.ArtifactStagingDirectory)/nupkg'
  displayName: 'Pack NuGet Package'

# Step 5: Push the NuGet package to Azure Artifacts Feed
- task: NuGetCommand@2
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/nupkg/*.nupkg'
    nuGetFeedType: 'azureFeed'
    feedPublishUrl: $(feedUrl)
  displayName: 'Push NuGet Package to Azure Artifacts'
