trigger:
- master

pool:
  name: Default  # Your self-hosted agent pool

variables:
  buildConfiguration: 'Release'
  feedName: 'MyNugetFeed'
  feedUrl: 'https://pkgs.dev.azure.com/mshar246/Assignment04/_packaging/MyNugetFeed/nuget/v3/index.json'

steps:
# Step 1: Authenticate with Azure Artifacts (CRITICAL)
- task: NuGetAuthenticate@1
  displayName: 'Authenticate NuGet Feed'

# Step 2: Restore packages using .NET Core CLI (better for SDK-style projects)
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Step 3: Build the project
- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: 'ShowCase/ShowCase.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Step 4: Create NuGet package
- task: DotNetCoreCLI@2
  displayName: 'Create NuGet Package'
  inputs:
    command: 'pack'
    packagesToPack: 'ShowCase/ShowCase.csproj'
    configuration: '$(buildConfiguration)'
    outputDir: '$(Build.ArtifactStagingDirectory)/nupkg'

# Step 5: Push to Azure Artifacts
- task: NuGetCommand@2
  displayName: 'Push to Azure Artifacts'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/nupkg/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(feedName)'

# (Optional) Step 6: Publish build artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'