trigger:
- master

pool:
  name: Default

variables:
  feedName: 'MyNugetFeed'
  feedUrl: 'https://pkgs.dev.azure.com/mshar246/Assignment04/_packaging/MyNugetFeed/nuget/v3/index.json'

steps:
# Step 0: Authenticate with Azure Artifacts (CRITICAL ADDITION)
- task: NuGetAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'

# Step 1: Install NuGet
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

# Step 2: Restore dependencies
- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: restore
    restoreSolution: 'Manav_DevOps_Assignment4.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'  # Point to your config file

# Step 3: Build
- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: 'ShowCase/ShowCase.csproj'
    arguments: '--configuration Release'

# Step 4: Pack
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package'
  inputs:
    command: 'pack'
    packagesToPack: 'ShowCase/ShowCase.csproj'
    configuration: 'Release'
    outputDir: '$(Build.ArtifactStagingDirectory)/nupkg'

# Step 5: Push (now properly authenticated)
- task: NuGetCommand@2
  displayName: 'Push to Azure Artifacts'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/nupkg/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(feedName)'