trigger:
- master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'
  feedName: 'MyNugetFeed'  # Must match exactly

steps:
# 1. Authentication (MUST come first)
- task: NuGetAuthenticate@1
  displayName: 'Authenticate NuGet'

# 2. Restore
- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: restore
    projects: '**/*.csproj'

# 3. Build
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: 'ShowCase/ShowCase.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 4. Pack
- task: DotNetCoreCLI@2
  displayName: 'Create Package'
  inputs:
    command: pack
    packagesToPack: 'ShowCase/ShowCase.csproj'
    configuration: '$(buildConfiguration)'
    outputDir: '$(Build.ArtifactStagingDirectory)/nupkg'

# 5. Push (Updated)
- task: NuGetCommand@2
  displayName: 'Push to Azure Artifacts'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/nupkg/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(feedName)'
    versioningScheme: 'off'

# 6. Optional: Publish artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'